language: node_js
node_js:
  - '5'
  - '4'
deploy:
  skip_cleanup: true
  provider: script
  script: ./scripts/deploy.sh
  'on':
    branch: master
    node: '5'
env:
  global:
    - secure: >-
        Tc6rpXZcoLp2sDrdR1IRrwkoU6w09hfq18XLuymu3FQ3T18MLTMB5XDmxRaC4h0LI3yRaI4DbfUAWWpzk5cF7uSJTWIdizyXQk2cveUhnJE/X5iLxvNjZZPNmohIiIyy5yFqEuI0LUZ2Ikaf7JPO/7NF5Zen/qofuc/x7EUHWEl2K/1EhZd4okkgbfPadfoB+Pv7R57ywqNcAvzGisO5Hr913MfDM9gLplkVfhDdpt1nXmcjNdW5/kFooSzWVDO+wVYKQj+dlS2n9xVkACzb9vuEpKc3EArqDr2Eer9fg1mjioOeq0dkoPhwAfTfertlRENJLwhHCF13qsPUbHlnJgUL5xJmFs8sDPnGfsBUGRwDlRRclI+mp/hdN8+YC97PtXuc/52NZxYB+qUauG6GpWYQRrG6BtxoKdJexwZ43JsqPNjTCAm1wGffb9bC6J6foR/yq/G46s/v2HMfDTyZAD3Np+mztlNh5QMJRuleXkvyWIw5wRnM+cePObRj3J8uKq4L69NF2txICErAMKYN5ukjaCdP5dZS+h5RnuZFPkC5ppgFF3NUTkd99L8znzyIQP3qgo+ya/D0dwmSrJ3pDj3zSS40ni38145BPapKxE9AeoEMXtugpC/MR6Rwc1UX9L9MxYBs1fbUx4SceqmsLlmcBHV2uSI3UPJQwr4GA9g=
    - GIT_DEPLOY_REPO=https://ab3cdbbb1c4e0cfdd593080acc807f8b5b1547c6@github.com/owenhoskins/phenomic-deploy.git